#!/usr/bin/env bash
# This script reconfigures host IP addresses directly from /etc/hosts

sudo cp /etc/hosts /etc/hosts.old

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
