#!/usr/bin/env bash
# Script that configures an Ubuntu server with specific requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Create a new hosts file with the required changes
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i 's/127.0.0.1\tip6-localhost/127.0.0.2\tip6-localhost/g' ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new

# Replace the system's hosts file with our new one
cp -f ~/hosts.new /etc/hosts 