#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Method 1: Using ifconfig if available
if command -v ifconfig &> /dev/null; then
    ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | cut -b 6- | sort
# Method 2: Using ip command if ifconfig isn't available
elif command -v ip &> /dev/null; then
    ip -4 addr show | grep -Eo 'inet ([0-9]*\.){3}[0-9]*' | cut -b 6- | sort
# Method 3: Fallback method using hostname
else
    hostname -I | tr ' ' '\n' | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' | sort
fi
